### ISSUE TITLE
Remote branch kibana-ruby not found

### ISSUE THREAD

**Issue by ryanvanderpol** [stephen-mw/Logstash_kibana_auto_install#7]
I can't get the install script to install Kibana.  Looks like it's trying to pull down code from a Github branch that does not exist.  Here's the output from the console:

```
~/Logstash_kibana_auto_install
/opt ~/Logstash_kibana_auto_install
Cloning into 'Kibana'...
remote: Counting objects: 38418, done.
remote: Compressing objects: 100% (12548/12548), done.
remote: Total 38418 (delta 24635), reused 38418 (delta 24635)
Receiving objects: 100% (38418/38418), 38.25 MiB | 2.89 MiB/s, done.
Resolving deltas: 100% (24635/24635), done.
warning: Remote branch kibana-ruby not found in upstream origin, using HEAD instead
/opt/Kibana /opt ~/Logstash_kibana_auto_install
sed: can't read KibanaConfig.rb: No such file or directory
```

It seems like everything prior to this installed correctly (redis, elasticsearch, logstash).

**Comment by stephen-mw** [comment]
Thanks for opening the ticket and sorry for the delay. I fixed the github repo (it was renamed to kibana2). I added some CI tests and it looks good now so I'm closing.
